# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='last_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='salesperson',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
