# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160426_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
