# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160426_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesaccounts',
            name='lead_sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SalesPerson'),
        ),
    ]
