# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20160426_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesaccounts',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.SalesPerson', unique=True),
        ),
    ]
